[".local/share/gedit/styles/nord.xml"]
  type = "file"
  url = "https://raw.githubusercontent.com/nordtheme/gedit/develop/src/xml/nord.xml"
  refreshPeriod = "168h"
[".local/share/fonts/caskaydia-cove"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/CascadiaCode.zip"
  exclude = ["*.md", "*Windows Compatible*", "LICENSE*"]
  refreshPeriod = "168h"
[".local/share/fonts/fura-mono"]
  type = "archive"
  url = "https://github.com/ryanoasis/nerd-fonts/releases/latest/download/FiraMono.zip"
  exclude = ["*.md", "*Windows Compatible*", "LICENSE*"]
  refreshPeriod = "168h"
[".local/share/fonts/fira-sans"]
  type = "archive"
  url = "https://fonts.google.com/download?family=Fira%20Sans"
  exclude = ["OFL.txt"]
  refreshPeriod = "168h"
[".local/share/fonts/earwig-factory"]
  type = "archive"
  url = "https://www.1001fonts.com/download/earwig-factory.zip"
  exclude = ["*.pdf"]
  refreshPeriod = "168h"
[".themes/Nordic-darker-v40"]
  type = "archive"
  url = "https://github.com/EliverLara/Nordic/releases/latest/download/Nordic-darker-v40.tar.xz"
  stripComponents = 1
  exclude = ["Nordic-darker-v40/gnome-shell/gnome-shell.css"]
  refreshPeriod = "168h"
[".icons/Nordic-cursors"]
  type = "archive"
  url = "https://github.com/EliverLara/Nordic/archive/refs/heads/master.zip"
  exact = true
  stripComponents = 4
  include = ["*/kde/cursors/Nordic-cursors/**"]
  refreshPeriod = "168h"
[".icons"]
  type = "archive"
  url = "https://github.com/PapirusDevelopmentTeam/papirus-icon-theme/archive/refs/heads/master.zip"
  stripComponents = 1
  include = ["*/Papirus/**"]
  refreshPeriod = "168h"
[".icons/Papirus/64x64/places"]
  type = "archive"
  url = "https://github.com/Adapta-Projects/Papirus-Nord/releases/latest/download/Papirus-Nord.tar.xz"
  stripComponents = 2
  include = ["Icons/64x64/**"]
  refreshPeriod = "168h"
[".icons/Papirus/48x48/places"]
  type = "archive"
  url = "https://github.com/Adapta-Projects/Papirus-Nord/releases/latest/download/Papirus-Nord.tar.xz"
  stripComponents = 2
  include = ["Icons/48x48/**"]
  refreshPeriod = "168h"
[".icons/Papirus/32x32/places"]
  type = "archive"
  url = "https://github.com/Adapta-Projects/Papirus-Nord/releases/latest/download/Papirus-Nord.tar.xz"
  stripComponents = 2
  include = ["Icons/32x32/**"]
  refreshPeriod = "168h"
[".icons/Papirus/24x24/places"]
  type = "archive"
  url = "https://github.com/Adapta-Projects/Papirus-Nord/releases/latest/download/Papirus-Nord.tar.xz"
  stripComponents = 2
  include = ["Icons/24x24/**"]
  refreshPeriod = "168h"
[".icons/Papirus/22x22/places"]
  type = "archive"
  url = "https://github.com/Adapta-Projects/Papirus-Nord/releases/latest/download/Papirus-Nord.tar.xz"
  stripComponents = 2
  include = ["Icons/22x22/**"]
  refreshPeriod = "168h"
[".local/bin/jq"]
  type = "file"
  url = "https://github.com/stedolan/jq/releases/latest/download/jq-linux64"
  executable = true
  refreshPeriod = "168h"
